<?php
return <<<SQL
INSERT INTO content_types (name,title,description,config,deleted_at) VALUES
	('oxy_intro','Oxy intro','','{}',NULL),
	('oxy_sintomas','Oxy sintomas','','{"HTMLTag": "form"}',NULL),
	('oxy_opciones','Oxy opciones','','{}',NULL),
	('oxy_kit','Oxy kit de tratamiento','','{}',NULL),
	('oxy_grave','Oxy grave','','{}',NULL),
	('oxy_step_exfolia','Oxy step exfolia','','{}',NULL),
	('oxy_step_refuerza','Oxy step refuerza','','{}',NULL),
	('oxy_step','Oxy step','','{}',NULL),
	('medical_survey','medical_survey','','{}',NULL),
	('page','page','','{}',NULL),
	('schema_acne_1','Acné schema #1','','{}',NULL),
	('schema_acne_2','Acné schema #2','','{}',NULL),
	('schema_acne_3','Acné schema #3','','{}',NULL),
	('schema_desc_text','Simple page schema','','{}',NULL),
	('schema_medical_page','Acne medical page info','','{}',NULL),
	('schema_treatment_result','Acné treatment result schema','','{}',NULL),
	('constipation_scheme_1','Constipation scheme #1','Constipation scheme #1','{}',NULL),
	('constipation_scheme_2','Constipation scheme #2','Constipation scheme #2','{}',NULL),
	('constipation_scheme_3','Constipation scheme #3','Constipation scheme #3','{}',NULL),
	('constipation_scheme_4','Constipation scheme #4','Constipation scheme #4','{}',NULL),
	('constipation_scheme_5','Constipation scheme #5','Constipation scheme #5','{}',NULL),
	('process_intestine_scheme','Process Intestine Scheme','Process Intestine Scheme','{}',NULL),
	('intestine_scheme_one','intestine scheme one','intestine scheme one','{}',NULL),
	('intestine_scheme_two','Intestine scheme two','Intestine scheme two','{}',NULL),
	('intestine_scheme_three','Intestine scheme tree','Intestine scheme tree','{}',NULL),
	('intestine_medical_schema','intestine medical schema','intestine medical schema','{}',NULL),
	('campaign_schema','Campaign schema','Campaign schema','{}',NULL)
SQL;