<?php
return <<<SQL
INSERT INTO fields (type,name,title,description,config,deleted_at) VALUES
	(1,'image_product','Image product','','{}',NULL),
	(11,'image','Simple image','Representa una dirección web de una imagen','{}',NULL),
	(1,'container','Container','Contenedor simple','{}',NULL),
	(4,'header_1','Header #1','Representa un encabezado H1','{}',NULL),
	(12,'button','Button','Representa un botón','{}',NULL),
	(12,'hr','Separator bar','Representa una linea separadora','{}',NULL),
	(5,'text','Text block','Bloque de texto extenso','{}',NULL),
	(4,'header_3','Header #3','Representa un encabezado H3','{}',NULL),
	(4,'header_6','Header #6','Representa un encabezado H6','{}',NULL),
	(1,'galery','Simple image galery','Lista de imagenes para galería de imágenes','{"HTMLTag": "form"}',NULL),
	(12,'span','Span','Cadena de texto','{}',NULL),
	(1,'list','Item list','Representa un listado de elementos','{}',NULL),
	(1,'text_list','Text list','Listado de cadenas de texto','{}',NULL),
	(4,'header_2','Header #2','Representa un encabezado H2','{}',NULL),
	(1,'bluelabel','bluelabel','Bloque de texto en forma de etiqueta azul','{}',NULL),
	(1,'input_number','Input type number','Campo númerico','{}',NULL),
	(1,'input_text','Input type text','Cadena de texto simple','{}',NULL),
	(1,'list_checkbox_question','Checkbox list','Pregunta de opción multiple con respuestas visuales','{}',NULL),
	(1,'accordion','Accordion','Acordeon simple (Titulo/contenido)','{}',NULL),
	(1,'treatment_block','Treatment Block','Bloque compuesto para lista de tratamientos','{}',NULL),
	(1,'product_reference','Product item reference','Bloque compuesto para lista de tratamientos','{}',NULL),
	(1,'product_list','Product list','Listado de productos para con funcionamiento de añadir al carrito','{}',NULL),
	(1,'list_image_question','list_image_question','Pregunta con respuestas en forma de imagen','{}',NULL),
	(1,'button_process_answers','button_process_answers','Botón que redirecciona al usuario según sus respuestas','{}',NULL),
	(1,'list_link_question','List link question','Lista de preguntas con redirección','{}',NULL),
	(7,'link','URL link','Representa una dirección web','{"default": {"url": "", "text": ""}, "placeholder": "Inserte una dirección web valida"}',NULL),
	(7,'link_medical_custom','Custom medical link','','{}',NULL),
	(7,'link_continue','Button link style #continue','Representa una dirección web','{"default": {"url": "", "text": ""}, "placeholder": "Inserte una dirección web valida"}',NULL),
	(1,'list_checkbox_types','List checkbox types','List checkbox types','{"default": {"color": "", "image": "", "title": "", "description": ""}, "placeholder": "Inserte una lista de opciones con su titulo, descripción e imagen"}',NULL),
	(1,'list_link','List link','A list of links','{"default": [], "placeholder": "Inserte los enlaces deseados"}',NULL),
	(1,'link_image','Link image','Link image','{"default": {"alt": "", "url": "", "image": "", "title": ""}, "placeholder": "Bloque de imagen con enlace"}',NULL),
	(1,'list_link_content','List link content','List link content','{}',NULL),
	(1,'content_lifestyle','Content lifestyle','Content lifestyle','{}',NULL),
	(1,'lifestyle_block','Lifestyle block','Lifestyle block','{}',NULL)
SQL;